### ISSUE TITLE
Missing supervisor

### ISSUE THREAD

**Issue by Pouriya-Jahanbakhsh** [processone/xmpp#25]
Hi. Why [Here](https://github.com/processone/xmpp/blob/master/src/xmpp.erl#L113) you did not start a supervisor instead ? I'm using some monitoring tools for monitoring Ejabberd and they get supervisor's children in runtime and here (`self()`) does not send response for supervisor API functions and causes some errors and timeouts on those Tools. for example [Wobserver](https://github.com/shinyscorpion/wobserver) in [here](https://github.com/shinyscorpion/wobserver/blob/v0.1.8/lib/wobserver/util/application.ex#L95) tries to make graph for supervision tree of an OTP application.

**Comment by zinid** [comment]
But why would we need a supervisor? Not every Erlang applications require a supervisor.

**Comment by Pouriya-Jahanbakhsh** [comment]
Yeah. but you defined a pid that should be root supervisor of application but is not.

**Comment by tsloughter** [comment]
Right, it shouldn't be returning a pid, there should be no `start/2` in `xmpp.erl` if it is to be a library application. I see it starts/loads deps in start but those should just be listed under applications in `xmpp.app.src` and jid nif can be loaded with `-on_load` instead of needing to call `jid:start` in `start/2`.
